### ISSUE TITLE
JR feedback

### ISSUE THREAD

**Issue by jread-usgs** [USGS-R/ds-pipelines-3-course#18]
` # TODO: PULL SITE DATA HERE` isn't in the original remake file nor covered in the previous issue?

https://github.com/jread-usgs/ds-pipelines-3/issues/4#issuecomment-637237803 makes it seem like you should do all three, but maybe WI?

> Set the include argument to c() in create_task_makefile(), build the remakefile again with scmake('state_tasks'), and run remake::diagram(remake_file='123_state_tasks.yml'). Do you understand the resulting message?

Should we call this an error instead of a message? (I assume we're looking for 
```
Error in .remake_add_targets_implied(obj) : 
  Implicitly created targets must all be files:
 - oldest_active_sites: (in WI_data, MN_data, MI_data)
 - parameter: (in WI_data, MN_data, MI_data)
```

should we ask them to .gitignore `.remake/` too?

> Add the lubridate package to the packages argument in your create_task_makefile() call (it's used in tally_site_obs()).

And `ggplot2` at this time?

> Check the contents of the 2_visualize/out directory and inspect at least one of the plots. How do they look?

Typo, should be 3_visualize

for split-apply-combine PR Wondering if we should encourage putting sources into arguments to do_state_tasks() instead of as depends. Otherwise, they are duplicated (once in the yaml and once inside the function)

Do you want this

> Implementation
The scipiper way to use combiners is to work with the finalize_funs, final_targets, as_promises, and tickquote_combinee_objects arguments to create_task_makefile(). Once you've set up these arguments properly, create_task_makefile() will write combiner targets into your task remakefile for you, autopopulating the arguments to match the final step of each task.

> The finalize_funs argument is a vector of one or more function names, each one of which will be called as the command to create a combiner target. Note that you don't get to specify anything else about your combiners here except their names. You can write your own combiner function or you can use the built-in combine_to_ind() combiner for a common type of combining (you'll see when we try it out). If you write your own combiner function, it should be defined within one of the sources or packages specified in create_task_makefile().

To me check boxes instead of bullets? To match with other sections? 

For
> function(ind_file, ...)

Perhaps use `filename` instead of `ind_file` to make it clear this can be any type of file? 

in https://github.com/jread-usgs/ds-pipelines-3/issues/10#issuecomment-637692334 do you need to also make sure they set `final_steps = 'tally'` in `create_task_plan`?

also, I'm wondering why we wouldn't instead suggest they do this
```r
  combined_tally <- scmake('combined_tally', remake_file=remakefile)
  return(combined_tally)
```
At the end of `do_state_tasks()`, that way the variable names don't matter, and the variable in the parent remake can be different or the same if you want. 
**update** now I understand this, because that pattern doesn't support patterns where you have more than one `final_targets`

in `plot_data_coverage`, should argument 1 be out_file (it is now arg 2) so we can follow our suggestion to have `target_name` be arg 1 when applicable? 

in 
```r
oldest_site_tallies %>%
    mutate(NumObsBin = cut(NumObs, breaks=c(0,100,200,300,364,366))) %>%
    ggplot(aes(x=Year, y=sprintf('%s-%s', State, Site), fill=NumObsBin)) + geom_tile() +
    ylab('State-Site') +
    ggtitle('Observation counts for champion %s sites', tolower(oldest_site_tallies$Parameter[1])) +
    scale_fill_brewer('Obs per Year') + theme_bw() -> p
```
The `Parameter` column is going to be missing from `oldest_site_tallies` (see instructor data.frame [here](https://github.com/jread-usgs/ds-pipelines-3/issues/10#issuecomment-637692334) )

**Comment by jread-usgs** [comment]
'123_state_tasks.R' needs to be an input to `do_state_tasks` to catch changes in combiner functions (unless they are written in other files)

**Comment by jread-usgs** [comment]
`target_name` works in `pluck()` for objects

```yaml
  obs_tallies:
    command: pluck(state_combiners, target_name)

  timeseries_plots_info:
    command: pluck(state_combiners, target_name)
```

**Comment by aappling-usgs** [comment]
- [x] # TODO: PULL SITE DATA HERE isn't in the original remake file nor covered in the previous issue? _should be there now_

- [ ] jread-usgs/ds-pipelines-3#4 (comment) makes it seem like you should do all three, but maybe WI? _I don't really understand the suggestion. Are you concerned that the example only shows WI at first? I think that's intentional (meant to help you diagnose your code changes one change at a time, before adding the list of states in this case). The initial `return()` code has:
  ```r
    return(list(
    example_target_name = download_step$target_name(task_name='WI', step_name='download'),
    example_command = download_step$command(task_name='WI', step_name='download')
  ))
  ```

- [x] `Set the include argument to c() in create_task_makefile(), build the remakefile again with scmake('state_tasks'), and run remake::diagram(remake_file='123_state_tasks.yml'). Do you understand the resulting message?` Should we call this an error instead of a message? _sure, done_

- [x] should we ask them to .gitignore .remake/ too? _done_

- [x] `Add the lubridate package to the packages argument in your create_task_makefile() call (it's used in tally_site_obs()).` And ggplot2 at this time? _shouldn't need it because ggplot2 is part of tidyverse core (see https://tidyverse.tidyverse.org)_

- [x] `Check the contents of the 2_visualize/out directory and inspect at least one of the plots. How do they look?` Typo, should be 3_visualize _changed, thanks_

- [ ] for split-apply-combine PR Wondering if we should encourage putting sources into arguments to do_state_tasks() instead of as depends. Otherwise, they are duplicated (once in the yaml and once inside the function)

- [ ] Do you want this ("The scipiper way to use combiners..." to me check boxes instead of bullets? To match with other sections? _no, because i don't want people modifying code as they're reading these particular bullets. but i have looked through other parts of the course and tried to make all actions into checkboxes._

- [x] For "function(ind_file, ...)" Perhaps use filename instead of ind_file to make it clear this can be any type of file? _done_

- [x] in jread-usgs/ds-pipelines-3#10 (comment) do you need to also make sure they set final_steps = 'tally' in create_task_plan? _this already happens in 51-code-a-combiner.md, though maybe it wasn't that way when you reviewed the course_

- [ ] in plot_data_coverage, should argument 1 be out_file (it is now arg 2) so we can follow our suggestion to have target_name be arg 1 when applicable?

- [x] in plot_data_coverage.R the Parameter column is going to be missing from oldest_site_tallies _fixed_

**Comment by aappling-usgs** [comment]
done!
